// Service Worker — auto-generated by PWA 打包神器
// Cache key: 紫微斗數ai大師-v1
// Strategy: Stale-While-Revalidate (HTML) + Cache-First (assets)

const CACHE_NAME = '紫微斗數ai大師-v1';
const PRECACHE_URLS = [
    "/z1/index.html",
    "/z1/sw.js",
    "/z1/manifest.json",
    "/z1/icon.svg",
    "/z1/offline.html",
    "/z1/icon-192.png",
    "/z1/icon-512.png"
];

// Install: pre-cache assets
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => {
      return cache.addAll(PRECACHE_URLS).catch(err => {
        console.warn('[SW] Pre-cache partial failure:', err);
      });
    }).then(() => self.skipWaiting())
  );
});

// Activate: clean old caches
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.filter(k => k !== CACHE_NAME)
            .map(k => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

// Fetch strategy:
//   HTML documents → Stale-While-Revalidate（先給舊的，背景更新）
//   其他資源      → Cache-First（快取優先，離線可用）
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.protocol === 'chrome-extension:') return;

  const isDocument = event.request.destination === 'document' ||
                     event.request.headers.get('accept')?.includes('text/html');

  if (isDocument) {
    // Stale-While-Revalidate for HTML
    event.respondWith(
      caches.open(CACHE_NAME).then(cache =>
        cache.match(event.request).then(cached => {
          const fetchPromise = fetch(event.request).then(response => {
            if (response && response.status === 200) {
              cache.put(event.request, response.clone());
            }
            return response;
          }).catch(() => null);

          return cached || fetchPromise || caches.match('/z1/offline.html');
        })
      )
    );
  } else {
    // Cache-First for assets
    event.respondWith(
      caches.match(event.request).then(cached => {
        if (cached) return cached;
        return fetch(event.request).then(response => {
          if (!response || response.status !== 200 || response.type === 'opaque') {
            return response;
          }
          const cloned = response.clone();
          caches.open(CACHE_NAME).then(cache => cache.put(event.request, cloned));
          return response;
        }).catch(() => {
          if (event.request.destination === 'document') {
            return caches.match('/z1/offline.html');
          }
        });
      })
    );
  }
});
